name: Miferia Vite Component Package

on:
  push:
    branches: [main, develop]

jobs:
  build:
    # if: github.event_name == 'push' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i -g yarn
      - run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Setup node'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@getmiferia'
          cache: 'yarn'

      - name: Bump version
        id: bump_version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
        with:
          minor-wording: add,Adds,new
          major-wording: MAJOR,cut-major
          patch-wording: patch,fixes
          rc-wording: RELEASE,alpha

      - name: 'Setup node and npm registry'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: 'Build project'
        run: |
          yarn install --frozen-lockfile
          yarn cache clean
          yarn build
          yarn version --new-version "${{ steps.bump_version.outputs.tag }}" && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
