name: Build tag and push
on:
  push:
    branches:
      - develop

jobs:
  publish_tag_package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@getmiferia'

      - name: Install dependencies
        run: |
          npm i -g yarn
          yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Bump version and push tag
        id: bump_version
        uses: getmiferia/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - run: |
          git config --global user.email "${{ github.actor }}@noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          echo "${{ steps.bump_version.outputs.tag }}"
      - run: yarn build
      - run: yarn version --new-version "${{ steps.bump_version.outputs.tag }}" && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}
